In [5]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[8,7]])
z=np.concatenate((x,y),axis=0)
z

array([[1, 2],
       [3, 4],
       [5, 6],
       [8, 7]])

In [8]:
#using arr.reshape()
import numpy as np
a=np.arange(6)
print(a)
a.shape

[0 1 2 3 4 5]


(6,)

In [15]:
b=a.reshape(3,-1)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [16]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[a>=6]
b

array([ 6,  7,  8,  9, 10, 11, 12])

In [17]:
divisibleBy3=a[a%3==0]
divisibleBy3

array([ 3,  6,  9, 12])

In [ ]:
#vstack and hstack  to be done

In [2]:
import numpy as np
x=np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [3]:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [4]:
b2=x.copy()
b2[0][3]=40
print("This is B2 :",b2)
print("This is X :",x)


This is B2 : [[ 1  2  3 40  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
This is X : [[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [41]:
d=divisibleBy3[1:]
d[0]=20
print("Sliced array is ",d)
print("Original array is ",divisibleBy3)

Sliced array is  [20  9 12]
Original array is  [ 3 20  9 12]


In [42]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.view()
x[0]=40
print("The original array->",arr)
print("The array x->",x)

The original array-> [40  2  3  4  5]
The array x-> [40  2  3  4  5]


In [62]:
a1=np.arange(5)
a2=np.array([5,6,7,8,9])
a3=a1+a2
a3


array([ 5,  7,  9, 11, 13])

In [60]:
b1=[[1,2,3,4],[5,6,7,8],[10,11,12,13]]
b2=[[8,7,6,5,4],[3,2,2,1],[1,2,3,4]]
b3=b2+b1
b3

[[8, 7, 6, 5, 4],
 [3, 2, 2, 1],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [5, 6, 7, 8],
 [10, 11, 12, 13]]

In [67]:
a=np.array([11,11,12,13,14,15,16,17,12,13,11,14,18,19,20])
unique_values,indices_list=np.unique(a,return_index=True)
print(indices_list)
print(unique_values)

[ 0  2  3  4  5  6  7 12 13 14]
[11 12 13 14 15 16 17 18 19 20]


In [68]:
arr=np.array([1,2,3,4,5,6,7,8])
reversed_arr=np.flip(arr)
print("The reversed array is :",reversed_arr)

The reversed array is : [8 7 6 5 4 3 2 1]
