In [22]:
import numpy as np
lis=[123,50,320]
arr=np.array(lis)
arr1=arr*2
arr1

array([246, 100, 640])

In [15]:
a=np.array(3) #don't forget []
a

array(3)

In [17]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [30]:

a=np.array([[1,2.4,3,4],[5,6,7,8],[9,10,11,12]])#n-dimensional which is also called "axis"
a

array([[ 1. ,  2.4,  3. ,  4. ],
       [ 5. ,  6. ,  7. ,  8. ],
       [ 9. , 10. , 11. , 12. ]])

In [24]:
a.ndim


2

In [31]:
a.shape

(3, 4)

In [32]:
len(a.shape)==a.ndim


True

In [33]:
a.size #total number of the elements

12

In [38]:
a.dtype

dtype('float64')

In [41]:
np.zeros

<function numpy.zeros>

In [42]:
np.empty(4)

array([0.0000000e+000, 1.0727584e-311, 1.0727584e-311, 1.0727584e-311])

In [43]:
np.zeros(4)

array([0., 0., 0., 0.])

In [44]:
np.ones(4)

array([1., 1., 1., 1.])

In [4]:
import numpy as np
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [51]:
x=np.ones(2,dtype=np.int32)
x

array([1, 1], dtype=int32)

In [2]:
import numpy as np
a=np.array([[1,4],[3,1]])
print(a)
print("\n")
b=np.sort(a)
print(b)
print("\n")
c=np.sort(a,axis=None)
print(c)
print("\n")
d=np.sort(a,axis=0)
print(d)

[[1 4]
 [3 1]]


[[1 4]
 [1 3]]


[1 1 3 4]


[[1 1]
 [3 4]]
